export enum TienLenEffect {
  NONE = "NONE",
  JACKPOT = "JACKPOT",

  WINNING = "WINNING",
  PASSING_TURN = "PASSING_TURN",

  SINGLE_TWO_PLAYED = "SINGLE_TWO_PLAYED",
  PAIR_TWO_PLAYED = "PAIR_TWO_PLAYED",
  THREE_TWO_PLAYED = "THREE_TWO_PLAYED",

  THREE_CONSECUTIVE_PAIR_BOOM = "THREE_CONSECUTIVE_PAIR_BOOM",
  FOUR_OF_KIND_BOOM = "FOUR_OF_KIND_BOOM",
  FOUR_CONSECUTIVE_PAIR_BOOM = "FOUR_CONSECUTIVE_PAIR_BOOM",
}

export default TienLenEffect;